WIP: elastic search adapter
bedita/elastic-search pull request #2
Opened 2023-06-26 09:58 UTC by didoda

2023-06-30 13:04 UTC, fquffio requested changes

2023-06-30 14:02 UTC, didoda commented on tests/TestCase/Adapter/ElasticSearchAdapterTest.php
> +        sleep(1);
nevermind, it was a test...

2023-06-30 14:19 UTC, didoda commented on phpstan.neon.dist
> +  level: 5
I pushed again level 9. Let's see how many errors we have to fix

2023-07-03 05:58 UTC, didoda commented on phpstan.neon.dist
> +  level: 5
Level is 9, now, but with some "ignoreErrors" in `phpstan.neon.dist` and few `@phpstan-ignore-next-line` in code

2023-07-05 09:57 UTC, fquffio approved these changes

2023-07-05 09:57 UTC, fquffio commented on phpstan.neon.dist
> +    - "#Property [a-zA-Z0-9\\$\\_\\\\:\\(\\)]+ type has no value type specified in iterable type array#"
These specific errors could be ignored using `checkMissingIterableValueType: false` ([docs](https://phpstan.org/config-reference#vague-typehints)):

```suggestion
  checkMissingIterableValueType: false
```

2023-07-05 10:27 UTC, merged